### ISSUE TITLE
Configure resources in radixconfig per cluster

### ISSUE THREAD

**Issue by nilsgstrabo** [equinor/radix-cost-allocation-api#128]
Memory requirements are different for each cluster (dev, playground, platform and C2).
1500Mi per pod in qa and prod environment is way too much for dev, playground and c2.
In dev we only use query the qa environment, and in playground, platform and c2, only the prod environment is used.

The generated radixconfigs for each cluster should also allow customizing memory requests as we do for other cluster specific configurations in Makefile. The values should be based on actual utilization in each cluster.

**Comment by emirgens** [comment]
Not really applicable
